import { useState } from 'react'
import { ArrowLeft, ArrowRight, Plus, Trash2 } from 'lucide-react'
import type { ProjectNode, ProjectDataDefinition } from '../../types/project'
import type { SlrbData, SlrbGrade, SlrbPresence, SlrbSolid, SlrbSupport, SlrbMaterial, SlrbWorkKind } from '../../types/slrb'
import { useStore } from '../../store/useStore'
import { newId, findNode } from '../../lib/tree'
import { buildSlrbOutputModel, defaultSlrbData, resizeSlrbLayout, slrbSolid, slrbWorkUnit } from '../../lib/slrb'
import { slrbDrawingSvg, slrbDetailSvg } from '../../lib/slrbDrawing'
import { dashboardContextMatches, dashboardItemIsSynced, dashboardComponentCompileSignature, collectDashboardItems } from '../../lib/dashboardSync'
import { slrbReferenceExample } from '../../lib/slrbExamples'
import { SLRB_MATERIAL_CANDIDATES } from '../../lib/slrbMaterials'
import { fetchSsrItems, type MasterItem } from '../../lib/masterData'
import { slrbReportData } from '../../lib/slrbReport'
import UnifiedCodePicker from '../templates/UnifiedCodePicker'
import Modal from '../modals/Modal'

const CHAPTERS=[
  ['Start & references','Use the information you already have. Record its source before relying on the measurements.'],
  ['Crossing & height','Confirm where each height starts and ends. Unknown heights remain pending.'],
  ['Layout & spans','An abutment holds each end. A pier is a support between the ends.'],
  ['Deck & approaches','Measure the actual concrete panels and surface layers shown in the detail.'],
  ['Supports & foundations','Describe each separate body, cap, footing, bedding and excavation.'],
  ['Walls & fittings','Add only the physical parts shown. Unknown and absent are different answers.'],
  ['Reinforcement & checks','Use complete bar lengths and counts from the reviewed schedule.'],
  ['Quantities & estimate','Review each measurement, then connect it to a compatible completed-work rate item.'],
  ['Review & outputs','Measurements, pricing and structural review have separate readiness states.']
]
const grades:SlrbGrade[]=['unknown','M10','M15','M20','M25','M30']
const fmt=(n:number|null|undefined):string=>n===null||n===undefined?'Pending':new Intl.NumberFormat('en-IN',{maximumFractionDigits:3}).format(n)
function NumberField({label,value,onChange,hint,unit='m'}:{label:string;value:number|null;onChange:(n:number|null)=>void;hint?:string;unit?:string}):JSX.Element {
  return <label className="slrb-field"><span>{label} ({unit})</span><input className="text-input" type="number" step="any" value={value??''} placeholder="Not known yet" onChange={e=>onChange(e.target.value.trim()===''||!Number.isFinite(Number(e.target.value))?null:Number(e.target.value))}/>{hint&&<small>{hint}</small>}</label>
}
function Choice<T extends string>({label,value,options,onChange}:{label:string;value:T;options:Array<[T,string]>;onChange:(v:T)=>void}):JSX.Element {
  return <label className="slrb-field"><span>{label}</span><select className="text-input" value={value} onChange={e=>onChange(e.target.value as T)}>{options.map(([v,text])=><option key={v} value={v}>{text}</option>)}</select></label>
}
function Presence({label,value,onChange}:{label:string;value:SlrbPresence;onChange:(v:SlrbPresence)=>void}):JSX.Element {
  return <Choice label={label} value={value} options={ [['unknown','I don’t know yet'],['provided','Yes — shown in the detail'],['none','No — confirmed absent']] } onChange={onChange}/>
}
function Grade({value,onChange}:{value:SlrbGrade;onChange:(g:SlrbGrade)=>void}):JSX.Element {
  return <Choice label="Concrete grade written in the detail" value={value} options={grades.map(g=>[g,g==='unknown'?'Not specified yet':g])} onChange={onChange}/>
}
function SolidFields({value,onChange,derivedHeight,excavation=false}:{value:SlrbSolid;onChange:(v:SlrbSolid)=>void;derivedHeight?:number|null;excavation?:boolean}):JSX.Element {
  const patch=(p:Partial<SlrbSolid>):void=>onChange({...value,...p})
  return <div className="slrb-fields">
    {!excavation&&<Choice label="Shape in the detail" value={value.shape} options={ [['rectangle','Rectangular prism'],['stadium','Rounded ends — stadium plan'],['trapezoid','Tapered / trapezoid section']] } onChange={shape=>patch({shape})}/>}
    <NumberField label="Length along the long face" value={value.length} onChange={length=>patch({length})}/>
    <NumberField label={value.shape==='trapezoid'?'Top thickness':'Width / end diameter'} value={value.width} onChange={width=>patch({width})}/>
    {value.shape==='trapezoid'&&<NumberField label="Bottom thickness" value={value.bottomWidth} onChange={bottomWidth=>patch({bottomWidth})}/>}
    {derivedHeight!==undefined?<div className="slrb-derived">Height from level stack: <strong>{fmt(derivedHeight)} m</strong></div>:<NumberField label={excavation?'Excavation depth':'Height / thickness'} value={value.height} onChange={height=>patch({height})}/>}
    {!excavation&&<Grade value={value.grade} onChange={grade=>patch({grade})}/>}
  </div>
}

export default function SlrbDashboard({node}:{node:ProjectNode}):JSX.Element {
  const project=useStore(s=>s.project)
  const save=useStore(s=>s.setSlrb)
  const select=useStore(s=>s.select)
  const editLocation=useStore(s=>s.openEditGeometry)
  const [chapter,setChapter]=useState(1)
  const [selected,setSelected]=useState('A1')
  const [picker,setPicker]=useState<string|null>(null)
  const [review,setReview]=useState<{key:string;material:SlrbMaterial}|null>(null)
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState('')
  const [chainage,setChainage]=useState('')
  if(!project) return <div className="slrb-dashboard">Open a project to use SLRB.</div>
  const current=findNode(project.root,node.id)??node
  const data=current.slrb??defaultSlrbData()
  if(data.schemaVersion!==1) return <div className="slrb-dashboard">This saved SLRB uses an unsupported schema version. Its data is retained; install a compatible addon before editing.</div>
  const model=buildSlrbOutputModel(project.root,current)
  const change=(patch:Partial<SlrbData>):void=>save(current.id,{...data,...patch})
  const changeSupport=(id:string,patch:Partial<SlrbSupport>):void=>change({supports:data.supports.map(s=>s.id===id?{...s,...patch}:s)})
  const support=data.supports.find(s=>s.id===selected)??data.supports[0]
  const chapterIssues=model.issues.filter(i=>i.chapter===chapter)
  const context=model.context
  const generated=current.children.filter(item=>item.kind==='item'&&item.templateGenerated&&item.templateOwnerId===current.id)
  const pricedItems=collectDashboardItems(current)
  const priceSynced=dashboardContextMatches(project.dashboardSnapshot,project)&&
    project.dashboardSnapshot?.componentCompileSignatures?.[current.id]===dashboardComponentCompileSignature(project,pricedItems)&&
    generated.length>0&&pricedItems.every(item=>dashboardItemIsSynced(project.dashboardSnapshot,item))
  const priceStatus=priceSynced ? model.mappingsReady?'Synced':'Known work synced — partial' : 'Needs component Sync'
  const memberOptions:Array<[string,string]>=[...data.spans.map((s,i)=>[s.id,`Span ${i+1}`] as [string,string]),...data.supports.map(s=>[s.id,s.id] as [string,string]),...data.approaches.map(a=>[a.id,a.id] as [string,string]),...data.walls.map(w=>[w.id,w.label] as [string,string]),...data.works.map(w=>[w.id,w.label] as [string,string])]
  const reviewMaster=(key:string,item:MasterItem):void=>{
    setReview({key,material:{code:item.code,description:item.description,unit:item.unit,side:item.side,categoryKey:item.category,dataVariant:item.dataVariant,sorCatalogue:item.sorCatalogue,
      reviewed:false,includesFormwork:Boolean(item.side==='SSR'&&/formwork|form work/i.test(item.description)),includesBackfill:Boolean(item.side==='SSR'&&/back.?fill/i.test(item.description)),scopeNote:''}})
  }
  const reviewProjectData=(key:string,definition:ProjectDataDefinition):void=>setReview({key,material:{code:definition.code,description:definition.description,unit:definition.unit,side:definition.kind==='ssr'?'SSR':'SOR',categoryKey:'project_data',projectDataId:definition.id,
    reviewed:false,includesFormwork:/formwork|form work/i.test(definition.description),includesBackfill:/back.?fill/i.test(definition.description),scopeNote:''}})
  const candidate=async(key:string):Promise<void>=>{
    const proposed=SLRB_MATERIAL_CANDIDATES[key]
    if(!proposed)return
    setBusy(true);setError('')
    try {const items=await fetchSsrItems('IRR-CCDW');const item=items.find(item=>item.code===proposed.code)
      if(!item)throw new Error(`Catalogue code ${proposed.code} is unavailable. Select a compatible project DATA or another code.`)
      reviewMaster(key,item)
    }catch(reason){setError(reason instanceof Error?reason.message:'Unable to read the catalogue.')}
    finally{setBusy(false)}
  }
  const mappingKeys=[...new Set(model.measurements.map(m=>m.mappingKey))]
  const exportBrief=():void=>{
    const blob=new Blob([JSON.stringify({package:{id:'e-estimate.slrb',version:data.packageVersion},componentId:current.id,model:slrbReportData(project,current)},null,2)],{type:'application/json'})
    const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='SLRB-review-snapshot.json';link.click();URL.revokeObjectURL(url)
  }
  return <div className="slrb-dashboard">
    <header className="slrb-header"><div><h1>{current.name}</h1><p>Single Lane Road Bridge · adopted geometry & estimate · addon {data.packageVersion}</p></div><button type="button" className="btn ghost" onClick={()=>select(current.id)}>Component dashboard</button></header>
    <div className="slrb-readiness"><span>Measurements: <strong>{model.measurementsReady?'Ready':'Needs information'}</strong></span><span>Pricing: <strong>{priceStatus}</strong></span><span>Rate items: <strong>{model.mappingsReady?'Mapped':'Needs review'}</strong></span><span>Design checks: <strong>{model.designStatus}</strong></span></div>
    <div className="slrb-layout"><nav className="slrb-chapters" aria-label="SLRB chapters">{CHAPTERS.map(([label],i)=><button type="button" key={label} className={chapter===i+1?'active':''} aria-current={chapter===i+1?'step':undefined} onClick={()=>setChapter(i+1)}><span>{i+1}</span>{label}<small>{model.issues.filter(issue=>issue.chapter===i+1).length||'✓'}</small></button>)}</nav>
    <main className="slrb-main"><h2>{chapter}. {CHAPTERS[chapter-1][0]}</h2><p className="slrb-orientation">{CHAPTERS[chapter-1][1]}</p>
    {chapter===1&&<>
      <div className="slrb-fields"><Choice label="What are you preparing?" value={data.purpose} options={ [['unknown','Help me build an information checklist'],['drawing','Estimate from a drawing / measurements'],['brief','Requirements for a new bridge']] } onChange={purpose=>change({purpose})}/>
      <Choice label="What is the status of your source?" value={data.sourceStatus} options={ [['unknown','Not sure yet'],['draft','Draft / unreviewed'],['reviewed','Reviewed for this project']] } onChange={sourceStatus=>change({sourceStatus})}/>
      <label className="slrb-field">Drawing / survey source, revision and detail<textarea className="text-input" value={data.reference} placeholder="Example: Bridge drawing B-04, Rev C, deck section" onChange={e=>change({reference:e.target.value})}/></label>
      <label className="slrb-field">Project loading class and design-code editions<input className="text-input" value={data.loadingBasis} placeholder="Use the designer’s specification; leave blank if unknown" onChange={e=>change({loadingBasis:e.target.value})}/></label></div>
      <p className="slrb-note">Requirements can be saved before dimensions are known. This addon does not size a bridge or verify structural safety.</p>
      <details><summary>Historical reference packages</summary><p>Load audited source candidates. Conflicts, actual panel lengths and missing schedules remain pending. This replaces the current bridge draft; Undo restores it.</p><div className="slrb-actions">{(['100835','102215'] as const).map(key=><button key={key} type="button" className="btn ghost" onClick={()=>save(current.id,{...slrbReferenceExample(key),materialItems:data.materialItems,acceptedParentId:data.acceptedParentId})}>Load km {key==='100835'?'100.835':'102.215'}</button>)}</div></details>
      {data.sourceConflicts.map(c=><section className="slrb-card" key={c.id}><strong>Source disagreement</strong><p>{c.message}</p><label className="slrb-field">Adopted value, active source and reason<input className="text-input" value={c.resolution} onChange={e=>change({sourceConflicts:data.sourceConflicts.map(old=>old.id===c.id?{...old,resolution:e.target.value,resolved:false}:old)})}/></label><label className="slrb-check"><input type="checkbox" checked={c.resolved} disabled={!c.resolution.trim()} onChange={e=>change({sourceConflicts:data.sourceConflicts.map(old=>old.id===c.id?{...old,resolved:e.target.checked}:old)})}/>I entered the adopted value in its chapter and recorded the reviewed source.</label></section>)}
    </>}
    {chapter===2&&<>
      <section className="slrb-card"><strong>Saved component location</strong><p>{current.location?`${current.location.lat.toFixed(6)}, ${current.location.lng.toFixed(6)}`:'Not recorded'}</p><button type="button" className="btn ghost" onClick={()=>editLocation(current.id)}>Edit existing location</button></section>
      {context.needsParentReview&&<section className="slrb-card"><p>The parent changed. Review the illustrated height source before adopting new quantities. Your manual heights are preserved.</p><button className="btn" type="button" onClick={()=>change({acceptedParentId:context.mode==='canal'?context.parentId:null})}>Use this parent’s height context</button></section>}
      {context.mode==='canal'?<>
        <section className="slrb-card"><strong>From Canal: {context.parentName}</strong><p>Crossing: {fmt(context.chainage)} m · parent revision {context.revision}</p><dl className="slrb-facts"><dt>Bed RL</dt><dd>{fmt(context.bedRl)}</dd><dt>Full supply RL</dt><dd>{fmt(context.fsl)}</dd><dt>Bank top RL</dt><dd>{fmt(context.bankRl)}</dd><dt>Bed width</dt><dd>{fmt(context.canal?.design.bedWidth)} m</dd><dt>Full supply depth</dt><dd>{fmt(context.canal?.design.fullSupplyDepth)} m</dd><dt>Discharge</dt><dd>{fmt(context.canal?.design.discharge)} m³/s</dd></dl><button className="btn ghost" type="button" onClick={()=>select(context.parentId)}>Open parent Canal</button>
          {context.issue&&<p className="slrb-note">{context.issue}</p>}
          <details><summary>Confirm a surveyed crossing chainage</summary><p>Use only the verified crossing on this parent alignment. A location/alignment edit invalidates this confirmation.</p><input className="text-input" aria-label="Surveyed crossing chainage in metres" type="number" value={chainage} onChange={e=>setChainage(e.target.value)}/><button type="button" className="btn ghost" disabled={chainage.trim()===''||!Number.isFinite(Number(chainage))||Number(chainage)<0||Number(chainage)>(context.canal?.lengthM??0)} onClick={()=>change({chainageOverride:Number(chainage),crossingConfirmationKey:context.locationKey})}>Use this chainage</button>{context.candidates.length>1&&<p>Nearby reaches: {context.candidates.map(ch=>fmt(ch)).join(', ')} m</p>}</details>
        </section>
        <div className="slrb-fields"><label className="slrb-field">Common level datum / survey reference<input className="text-input" value={data.datum} placeholder="All road, Canal and footing levels must use this datum" onChange={e=>change({datum:e.target.value})}/></label><Choice label="How is the finished road level given?" value={data.roadLevelMode} options={ [['absolute','Road RL from the drawing / survey'],['above-bank','Specified height above Canal bank top']] } onChange={roadLevelMode=>change({roadLevelMode})}/>{data.roadLevelMode==='absolute'?<NumberField label="Finished road RL" value={data.roadRl} onChange={roadRl=>change({roadRl})}/>:<NumberField label="Road above inherited bank top" value={data.roadBankOffset} onChange={roadBankOffset=>change({roadBankOffset})}/>}</div>
        <p className="slrb-note">Shaft/body height = road RL − wearing depth − slab depth − bearing/seat stack − cap depth − footing-top RL. Enter the deck/cap detail in Chapters 4–5. The inherited water depth alone does not set a support height.</p>
      </>:<p className="slrb-note">Enter the body/shaft height between the top of its footing and underside of its cap. Levels are optional for this bridge; no Canal hydraulic inputs are required.</p>}
      {data.supports.map(s=><section className="slrb-card" key={s.id}><button className="btn ghost" type="button" onClick={()=>setSelected(s.id)}>{s.id} — {s.kind}</button>{context.mode==='canal'?<><div className="slrb-fields"><Choice label="How is the footing-top level specified?" value={s.footingLevelMode} options={ [['absolute','Footing-top RL in the same datum'],['below-bed','Specified depth below inherited Canal bed']] } onChange={footingLevelMode=>changeSupport(s.id,{footingLevelMode})}/>{s.footingLevelMode==='absolute'?<NumberField label="Footing-top RL" value={s.footingTopRl} onChange={footingTopRl=>changeSupport(s.id,{footingTopRl})}/>:<NumberField label="Footing top below Canal bed" value={s.footingBedOffset} onChange={footingBedOffset=>changeSupport(s.id,{footingBedOffset})}/>}<NumberField label="Bearing / seat stack" value={s.bearingStack} onChange={bearingStack=>changeSupport(s.id,{bearingStack})} hint="Enter 0 only if the reviewed detail has no separate bearing/seat depth."/></div><p>Calculated height: <strong>{fmt(model.heights[s.id])} m</strong></p></>:<NumberField label={`${s.id} body / shaft height`} value={s.body.height} onChange={height=>changeSupport(s.id,{body:{...s.body,height}})} hint="Do not include footing, cap or deck thickness in this height."/>}</section>)}
    </>}
    {chapter===3&&<>
      <div className="slrb-fields"><NumberField label="Crossing angle" unit="degrees" value={data.crossingAngle} onChange={crossingAngle=>change({crossingAngle})} hint="This release measures a straight, square crossing: 90°."/><NumberField label="Structural slab width — outside to outside" value={data.slabWidth} onChange={slabWidth=>change({slabWidth})}/><NumberField label="Clear carriageway width" value={data.carriagewayWidth} onChange={carriagewayWidth=>change({carriagewayWidth})}/><label className="slrb-field">Number of spans<select className="text-input" value={data.spans.length} onChange={e=>save(current.id,resizeSlrbLayout(data,Number(e.target.value)))}>{Array.from({length:12},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label></div>
      <p>Ordered supports: <strong>{data.supports.map(s=>s.id).join(' → ')}</strong>. Intermediate piers: {data.supports.filter(s=>s.kind==='pier').length}.</p>
      {data.spans.map((span,i)=><section className="slrb-card" key={span.id}><h3>Span {i+1}</h3><div className="slrb-fields"><NumberField label="Clear opening between support faces" value={span.clearSpan} onChange={clearSpan=>change({spans:data.spans.map(s=>s.id===span.id?{...s,clearSpan}:s)})}/><NumberField label="Actual concrete panel length — end to end" value={span.panelLength} onChange={panelLength=>change({spans:data.spans.map(s=>s.id===span.id?{...s,panelLength}:s)})} hint="Includes the actual support-seat portions. An effective design span is not a concrete measurement."/></div><button type="button" className="btn ghost" onClick={()=>setSelected(span.id)}>Highlight this panel</button></section>)}
    </>}
    {chapter===4&&<>
      {data.spans.map((span,i)=><section className="slrb-card" key={span.id}><h3>Solid deck slab — span {i+1}</h3><div className="slrb-fields"><NumberField label="Slab thickness" value={span.thickness} onChange={thickness=>change({spans:data.spans.map(s=>s.id===span.id?{...s,thickness}:s)})}/><Grade value={span.grade} onChange={grade=>change({spans:data.spans.map(s=>s.id===span.id?{...s,grade}:s)})}/></div><p>Actual panel: {fmt(span.panelLength)} × {fmt(data.slabWidth)} m. Other deck systems require a reviewed measurement extension.</p></section>)}
      <section className="slrb-card"><Presence label="Is a wearing layer shown?" value={data.wearingPresence} onChange={wearingPresence=>change({wearingPresence})}/>{data.wearingPresence==='provided'&&<div className="slrb-fields"><NumberField label="Wearing thickness" value={data.wearingThickness} onChange={wearingThickness=>change({wearingThickness})}/><NumberField label="Covered width" value={data.wearingWidth} onChange={wearingWidth=>change({wearingWidth})}/><Grade value={data.wearingGrade} onChange={wearingGrade=>change({wearingGrade})}/></div>}</section>
      {data.approaches.map(a=><section className="slrb-card" key={a.id}><h3>{a.id} — approach at this end</h3><Presence label="Is an approach slab shown?" value={a.presence} onChange={presence=>change({approaches:data.approaches.map(old=>old.id===a.id?{...old,presence}:old)})}/>{a.presence==='provided'&&<><SolidFields value={a.slab} onChange={slab=>change({approaches:data.approaches.map(old=>old.id===a.id?{...old,slab}:old)})}/><Presence label="Is gravel backing shown below the approach?" value={a.backingPresence} onChange={backingPresence=>change({approaches:data.approaches.map(old=>old.id===a.id?{...old,backingPresence}:old)})}/>{a.backingPresence==='provided'&&<NumberField label="Backing depth" value={a.backingDepth} onChange={backingDepth=>change({approaches:data.approaches.map(old=>old.id===a.id?{...old,backingDepth}:old)})}/>}</>}</section>)}
    </>}
    {chapter===5&&support&&<>
      <Choice label="Choose a support" value={support.id} options={data.supports.map(s=>[s.id,`${s.id} — ${s.kind}`])} onChange={setSelected}/>
      <section className="slrb-card"><h3>{support.id} body / shaft</h3><SolidFields value={support.body} onChange={body=>changeSupport(support.id,{body})} derivedHeight={context.mode==='canal'?model.heights[support.id]:undefined}/></section>
      <section className="slrb-card"><Presence label="Is a separate cap shown?" value={support.capPresence} onChange={capPresence=>changeSupport(support.id,{capPresence})}/>{support.capPresence==='provided'&&<SolidFields value={support.cap} onChange={cap=>changeSupport(support.id,{cap})}/>}</section>
      <section className="slrb-card"><Choice label="Which foundation is specified?" value={support.footingType} options={ [['unknown','Not specified yet'],['spread','Spread footing'],['other','Piles / another foundation']] } onChange={footingType=>changeSupport(support.id,{footingType})}/>{support.footingType==='spread'?<SolidFields value={support.footing} onChange={footing=>changeSupport(support.id,{footing})}/>:<p>Request the foundation detail. Piles and other foundation systems need a reviewed schedule/extension.</p>}<p>Soil-bearing, stability and reinforcement design checks remain the designer’s responsibility. Specified footing quantities can be measured while those checks are pending.</p></section>
      <section className="slrb-card"><Presence label="Is levelling/bedding concrete shown?" value={support.beddingPresence} onChange={beddingPresence=>changeSupport(support.id,{beddingPresence})}/>{support.beddingPresence==='provided'&&<SolidFields value={support.bedding} onChange={bedding=>changeSupport(support.id,{bedding})}/>}</section>
      <section className="slrb-card"><Presence label="Are excavation dimensions supplied?" value={support.excavationPresence} onChange={excavationPresence=>changeSupport(support.id,{excavationPresence})}/>{support.excavationPresence==='provided'&&<SolidFields excavation value={support.excavation} onChange={excavation=>changeSupport(support.id,{excavation})}/>}<p>Use the approved excavation boundary, working space and depth. Backfill may already be included in the excavation rate item.</p></section>
    </>}
    {chapter===6&&<>
      <Presence label="Are wing / return walls shown?" value={data.wallsPresence} onChange={wallsPresence=>change({wallsPresence})}/>
      {data.wallsPresence==='provided'&&<><button className="btn ghost" type="button" onClick={()=>change({walls:[...data.walls,{id:newId(),label:`Wall ${data.walls.length+1}`,length:null,startHeight:null,endHeight:null,topThickness:null,bottomThickness:null,grade:'unknown',footingPresence:'unknown',footing:slrbSolid()}]})}><Plus size={15}/> Add a wall</button>{data.walls.map(w=><section className="slrb-card" key={w.id}><label className="slrb-field">Wall / drawing mark<input className="text-input" value={w.label} onChange={e=>change({walls:data.walls.map(old=>old.id===w.id?{...old,label:e.target.value}:old)})}/></label><div className="slrb-fields">{(['length','startHeight','endHeight','topThickness','bottomThickness'] as const).map(field=><NumberField key={field} label={({length:'Wall length',startHeight:'Height at start',endHeight:'Height at end',topThickness:'Top thickness',bottomThickness:'Bottom thickness'})[field]} value={w[field]} onChange={value=>change({walls:data.walls.map(old=>old.id===w.id?{...old,[field]:value}:old)})}/>)}<Grade value={w.grade} onChange={grade=>change({walls:data.walls.map(old=>old.id===w.id?{...old,grade}:old)})}/></div><p>For a linear change of height with constant top/bottom thicknesses. Split stepped or changing-thickness walls into separately measured pieces.</p><Presence label="Is a separate wall footing shown?" value={w.footingPresence} onChange={footingPresence=>change({walls:data.walls.map(old=>old.id===w.id?{...old,footingPresence}:old)})}/>{w.footingPresence==='provided'&&<SolidFields value={w.footing} onChange={footing=>change({walls:data.walls.map(old=>old.id===w.id?{...old,footing}:old)})}/>}<button className="btn ghost" type="button" onClick={()=>change({walls:data.walls.filter(old=>old.id!==w.id)})}><Trash2 size={15}/>Remove this wall</button></section>)}</>}
      <Presence label="Are kerbs, railings, joints or drains shown?" value={data.fittingsPresence} onChange={fittingsPresence=>change({fittingsPresence})}/>
      {data.fittingsPresence==='provided'&&<><button className="btn ghost" type="button" onClick={()=>change({works:[...data.works,{id:newId(),label:`Fitting ${data.works.length+1}`,kind:'kerb',presence:'unknown',length:null,width:null,depth:null,count:null,quantity:null,grade:'unknown',distinctScope:false,reference:''}]})}><Plus size={15}/>Add a fitting / distinct work</button>{data.works.map(w=><section className="slrb-card" key={w.id}><label className="slrb-field">Drawing mark / work label<input className="text-input" value={w.label} onChange={e=>change({works:data.works.map(old=>old.id===w.id?{...old,label:e.target.value}:old)})}/></label><Choice<SlrbWorkKind> label="What is this work?" value={w.kind} options={ [['kerb','Kerb concrete'],['rail-concrete','Concrete railing member'],['joint','Joint work — measured length'],['drain','Drain / spout count'],['fill','Distinct selected fill'],['gravel','Gravel backing'],['formwork','Separate formwork area']] } onChange={kind=>change({works:data.works.map(old=>old.id===w.id?{...old,kind}:old)})}/><Presence label="Is the detail supplied?" value={w.presence} onChange={presence=>change({works:data.works.map(old=>old.id===w.id?{...old,presence}:old)})}/>{w.presence==='provided'&&<div className="slrb-fields">{w.kind==='kerb'||w.kind==='rail-concrete'?<>{(['length','width','depth','count'] as const).map(field=><NumberField key={field} unit={field==='count'?'No.':'m'} label={field} value={w[field]} onChange={value=>change({works:data.works.map(old=>old.id===w.id?{...old,[field]:value}:old)})}/>)}<Grade value={w.grade} onChange={grade=>change({works:data.works.map(old=>old.id===w.id?{...old,grade}:old)})}/></>:<NumberField label="Reviewed work quantity" unit={slrbWorkUnit(w.kind)} value={w.quantity} onChange={quantity=>change({works:data.works.map(old=>old.id===w.id?{...old,quantity}:old)})}/>}</div>}<label className="slrb-field">Measurement / joint / railing detail reference<input className="text-input" value={w.reference} onChange={e=>change({works:data.works.map(old=>old.id===w.id?{...old,reference:e.target.value}:old)})}/></label>{(w.kind==='formwork'||w.kind==='fill')&&<label className="slrb-check"><input type="checkbox" checked={w.distinctScope} onChange={e=>change({works:data.works.map(old=>old.id===w.id?{...old,distinctScope:e.target.checked}:old)})}/>This is separate physical work outside the selected concrete/excavation item’s inclusions.</label>}<button className="btn ghost" type="button" onClick={()=>change({works:data.works.filter(old=>old.id!==w.id)})}>Remove this work</button></section>)}</>}
    </>}
    {chapter===7&&<>
      <Presence label="Do you have a complete reinforcement schedule?" value={data.reinforcementPresence} onChange={reinforcementPresence=>change({reinforcementPresence})}/><p className="slrb-note">A callout such as “20 @ 150” gives diameter and spacing, but not full bar length, anchorage or laps. Steel tonnage stays pending until the complete schedule is reviewed. Bar mass uses steel density 7,850 kg/m³; rate-analysis supply wastage is not added again.</p>
      {data.reinforcementPresence==='provided'&&<><button className="btn ghost" type="button" onClick={()=>change({bars:[...data.bars,{id:newId(),memberId:data.spans[0].id,mark:'',diameterMm:null,count:null,cutLengthM:null,shape:'',reference:'',reviewed:false}]})}><Plus size={15}/>Add a bar group</button>{data.bars.map(b=><section className="slrb-card" key={b.id}><div className="slrb-fields"><Choice label="Member" value={b.memberId} options={[...(memberOptions.some(([id])=>id===b.memberId)?[]:[[b.memberId,'Removed member — choose another'] as [string,string]]),...memberOptions]} onChange={memberId=>change({bars:data.bars.map(old=>old.id===b.id?{...old,memberId,reviewed:false}:old)})}/>{(['diameterMm','count','cutLengthM'] as const).map(field=><NumberField key={field} unit={field==='diameterMm'?'mm':field==='count'?'No.':'m'} label={field==='cutLengthM'?'Complete cut length per bar':field==='diameterMm'?'Diameter':'Whole bar count'} value={b[field]} onChange={value=>change({bars:data.bars.map(old=>old.id===b.id?{...old,[field]:value,reviewed:false}:old)})}/>)}{(['mark','shape','reference'] as const).map(field=><label className="slrb-field" key={field}>{field==='reference'?'BBS / detail reference':field==='shape'?'Bar shape, hooks, bends and laps':'Bar mark'}<input className="text-input" value={b[field]} onChange={e=>change({bars:data.bars.map(old=>old.id===b.id?{...old,[field]:e.target.value,reviewed:false}:old)})}/></label>)}</div><label className="slrb-check"><input type="checkbox" checked={b.reviewed} onChange={e=>change({bars:data.bars.map(old=>old.id===b.id?{...old,reviewed:e.target.checked}:old)})}/>Schedule checked: member, count, full shape/cut length and source apply to this project.</label><button className="btn ghost" type="button" onClick={()=>change({bars:data.bars.filter(old=>old.id!==b.id)})}>Remove this bar group</button></section>)}</>}
      <label className="slrb-field">Designer’s review reference / outstanding checks<textarea className="text-input" value={data.structuralReview} onChange={e=>change({structuralReview:e.target.value})}/></label><p>No structural pass is inferred from completing this form. Deck loading/bending, support stability, foundation bearing/shear and detailing need the appropriate reviewed design.</p>
    </>}
    {chapter===8&&<>
      <Choice label="Which estimating basis does the project prescribe?" value={data.estimateBasis} options={ [['unknown','Needs confirmation'],['irrigation-ssr','Applicable irrigation SSR'],['approved-other','Approved R&B / MoRTH / other analysis']] } onChange={estimateBasis=>change({estimateBasis})}/><p>Project year: {project.meta.sorYear} · zone: {project.meta.sorZone??'zone_3'}. Prices come from normal host Sync, including DATA Timely rates. Canal inheritance does not choose the billing schedule.</p>
      <div className="slrb-table-wrap"><table className="slrb-table"><thead><tr><th>Member / work</th><th>Measurement</th><th>Quantity</th><th>Unit</th><th>Rate item</th></tr></thead><tbody>{model.measurements.map(m=><tr key={m.id}><td><button type="button" className="slrb-link" onClick={()=>setSelected(m.memberId)}>{m.label}</button></td><td>{m.expression}</td><td>{fmt(m.quantity)}</td><td>{m.unit}</td><td>{m.billable?m.material?.code:'Pending review'}</td></tr>)}</tbody></table></div>
      {mappingKeys.map(key=><section className="slrb-card" key={key}><h3>{key}</h3><p>{data.materials[key]?.code??'No rate item adopted'} · {data.materials[key]?.description??'Choose a matching completed-work item or project DATA.'}</p>{SLRB_MATERIAL_CANDIDATES[key]&&<p>{SLRB_MATERIAL_CANDIDATES[key].note}</p>}{key==='rail-concrete.M20'&&<p>IRR-CCDW-5-5 describes RCC posts with GI pipes. It does not match concrete rails; use a compatible reviewed DATA.</p>}<div className="slrb-actions">{SLRB_MATERIAL_CANDIDATES[key]&&<button className="btn ghost" type="button" disabled={busy||data.estimateBasis!=='irrigation-ssr'} onClick={()=>void candidate(key)}>Review {SLRB_MATERIAL_CANDIDATES[key].code}</button>}<button className="btn ghost" type="button" onClick={()=>setPicker(key)}>Choose another code</button><select className="text-input" aria-label={`Use project DATA for ${key}`} value="" onChange={e=>{const def=project.projectData?.find(d=>d.id===e.target.value);if(def)reviewProjectData(key,def)}}><option value="">Use project DATA…</option>{project.projectData?.map(def=><option value={def.id} key={def.id}>{def.code} — {def.description}</option>)}</select>{data.materials[key]&&<button className="btn ghost" type="button" onClick={()=>change({materials:{...data.materials,[key]:undefined}})}>Remove mapping</button>}</div>{key==='wearing.M25'&&<p>The built-in M25 wearing-coat DATA is available above. Review its retained production assumptions for this project before adopting it.</p>}</section>)}
      {error&&<p role="alert" className="slrb-note">{error}</p>}<p className="slrb-note">Generated items represent only measurable, reviewed mappings. Missing work remains listed here. Open Component dashboard and Sync to calculate prices; its subtotal covers known items.</p>
    </>}
    {chapter===9&&<>
      <p>{model.measurements.filter(m=>m.quantity!==null).length} of {model.measurements.length} measurements have adopted dimensions. {current.children.filter(c=>c.templateGenerated&&c.templateOwnerId===current.id).length} ordinary estimate items are generated.</p>
      <div className="slrb-actions"><button type="button" className="btn" onClick={()=>select(current.id)}>Open component Sync, PDF & Excel</button><button type="button" className="btn ghost" onClick={exportBrief}>Download review snapshot</button></div><p>Component and project reports use this same versioned measurement model. The snapshot retains the current source, parent revision, measurements and pending issues. Earlier exports remain historical revisions.</p>
      {model.issues.map((issue,i)=><button type="button" className="slrb-issue" key={`${issue.memberId}-${i}`} onClick={()=>{setChapter(issue.chapter);setSelected(issue.memberId)}}><strong>Chapter {issue.chapter}</strong> · {issue.message}</button>)}
      {!model.issues.length&&<p>Measurements and rate-item mappings are ready. Use host Sync for pricing; structural review remains separate.</p>}
    </>}
    {chapterIssues.length>0&&chapter!==9&&<details className="slrb-pending"><summary>{chapterIssues.length} information / review actions in this chapter</summary>{chapterIssues.map((issue,i)=><p key={i}>{issue.message}</p>)}</details>}
    <footer className="slrb-footer"><button className="btn ghost" type="button" disabled={chapter===1} onClick={()=>setChapter(chapter-1)}><ArrowLeft size={15}/>Back</button><span>Changes save to the project; Undo is available.</span><button className="btn" type="button" disabled={chapter===9} onClick={()=>setChapter(chapter+1)}>Continue{chapterIssues.length?' with pending inputs':''}<ArrowRight size={15}/></button></footer>
    </main>
    <aside className="slrb-visual"><h3>Bridge parts & height endpoints</h3><div dangerouslySetInnerHTML={{__html:slrbDrawingSvg(data,model.heights,selected)}}/><div className="slrb-member-buttons">{memberOptions.map(([id,label])=><button type="button" className={id===selected?'active':''} key={id} onClick={()=>setSelected(id)}>{label}</button>)}</div>{chapter>1&&chapter<8&&<div dangerouslySetInnerHTML={{__html:slrbDetailSvg(data,model.heights,selected,chapter)}}/>}<p>Deck panels carry the road. A1/A2 are the ends; P1… are intermediate piers. Footings sit below the body; caps sit above it.</p><section className="slrb-card"><strong>Next useful action</strong><p>{chapterIssues[0]?.message??'Review the entered source and measurements, then continue to the next chapter.'}</p></section></aside>
    </div>
    {picker&&<UnifiedCodePicker title={`Choose rate item for ${picker}`} hint="Choose complete work matching this member, unit, grade and approved estimating basis." onPick={item=>reviewMaster(picker,item)} onClose={()=>setPicker(null)}/>}
    {review&&<Modal title={`Review ${review.material.code} for ${review.key}`} onClose={()=>setReview(null)} footer={<><button type="button" className="btn ghost" onClick={()=>setReview(null)}>Cancel</button><button type="button" className="btn" disabled={!review.material.reviewed||!review.material.scopeNote.trim()||data.estimateBasis==='unknown'||['material','labour','machinery'].includes(review.material.categoryKey??'')} onClick={()=>{change({materials:{...data.materials,[review.key]:review.material}});setReview(null)}}>Use this reviewed item</button></>}>
      <p>{review.material.description}</p><p>Unit: {review.material.unit}. Confirm the member’s grade, aggregate size, work scope and inclusions. Ingredient/supply prices do not replace a completed-work analysis.</p>{SLRB_MATERIAL_CANDIDATES[review.key]&&<p>{SLRB_MATERIAL_CANDIDATES[review.key].note}</p>}<label className="slrb-field">Applicable specification / scope decision<textarea className="text-input" value={review.material.scopeNote} onChange={e=>setReview({...review,material:{...review.material,scopeNote:e.target.value}})}/></label><label className="slrb-check"><input type="checkbox" checked={review.material.includesFormwork} onChange={e=>setReview({...review,material:{...review.material,includesFormwork:e.target.checked}})}/>This rate includes formwork.</label><label className="slrb-check"><input type="checkbox" checked={review.material.includesBackfill} onChange={e=>setReview({...review,material:{...review.material,includesBackfill:e.target.checked}})}/>This rate includes excavation backfilling.</label><label className="slrb-check"><input type="checkbox" checked={review.material.reviewed} onChange={e=>setReview({...review,material:{...review.material,reviewed:e.target.checked}})}/>I checked unit, grade, scope, estimating basis and overlapping inclusions against the project specification.</label>
    </Modal>}
  </div>
}
