/**
 * Component Report Typst Generator.
 *
 * Implements Option 1: Modular Inheritance & Separation of Concerns.
 *
 * The Component Report brings together:
 * 1. Component Title Banner & Project metadata
 * 2. Abstract of Estimate summary table (all items, quantities, rates, amounts, grand total)
 * 3. Child item detailed calculation sheets (Univer Spreadsheets) and narrative specifications (Univer Documents)
 * 4. Component-level signatures
 *
 * If a child item has a specialized single-item layout (e.g. Page 2 on A3), the estimator
 * configures it in that item's Print Studio, keeping this master component template
 * clean, maintainable, and straightforward.
 */

import defaultComponentTemplate from './component.typ?raw'
import univerComponentPrelude from './univerComponent.typ?raw'
import {
  EE_ITEM_TABLE_PRELUDE,
  itemSheetShadowFiles,
  resolveItemDescriptionRuns,
  type ExtractedMedia,
  type ItemMediaItem,
  extractItemMedia
} from './itemTypst'
import { extractDocumentMedia, parseDocumentToTypstData } from './documentTypst'
import { createUniverWorkbookData, usedCellRange } from '../univerSpreadsheet'
import { nodeDisplayName } from '../../components/nodeVisual'
import { findNode } from '../tree'
import { componentItemsTotal, getItemFinal } from '../finalNumber'
import { resolveNodeSettings, resolveNodeSettingsOverrides } from '../nodeSettings'
import {
  printableSignatureRows,
  resolveSignatureFooter
} from '../signatureFooter'
import {
  applyDocumentSettingsToTypst,
  normalizeDocumentSettings,
  parseDocumentSettingsFromTypst,
  resolveProjectDocumentSettings,
  type DocumentSettings
} from './documentSettings'
import type {
  EestimateProject,
  ProjectNode
} from '../../types/project'
import type { RateAnalysisRecipe, RateAnalysisTextRun } from '../../types/rateAnalysis'
import { bundCompileInputs, bundVariablesPrelude, injectBundLayout } from './bund/bundTypst'
import {
  guideWallCompileInputs,
  guideWallVariablesPrelude,
  injectGuideWallLayout
} from './guidewall/guideWallTypst'

const money = new Intl.NumberFormat('en-IN', {
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
})

const qtyFmt = new Intl.NumberFormat('en-IN', {
  maximumFractionDigits: 3
})

export interface ComponentAbstractRowData {
  sl: string
  code: string
  heading: string
  description: string
  qty: string
  rawQty: number | null
  unit: string
  rate: string
  rawRate: number | null
  amount: string
  rawAmount: number | null
}

export interface ComponentChildItemData {
  id: string
  code: string
  name: string
  unit: string
  description: string
  descriptionRuns: RateAnalysisTextRun[]
  editorType: 'spreadsheet' | 'document'
  /** True when the item was generated by a component template (e.g. bund), so a
   *  detail page should NOT be reprinted — the template's own layout covers it. */
  templateGenerated: boolean
  univer?: unknown
  document?: unknown
  printConfig: {
    pageSize: string
    orientation: string
    margins: { top: number; right: number; bottom: number; left: number }
    range?: { startRow: number; startColumn: number; endRow: number; endColumn: number } | [number, number, number, number] | null
    repeatHeaderRows?: number
    showGridlines?: boolean
  }
  images?: unknown[]
}

export interface ComponentRenderData {
  project: string
  component: {
    id: string
    name: string
    code: string
    isSubcomponent: boolean
    totalCost: number
    totalFormatted: string
  }
  abstract: ComponentAbstractRowData[]
  items: ComponentChildItemData[]
  signature: Array<{ designation: string; office: string }>
  gallery?: ItemMediaItem[]
  images?: ItemMediaItem[]
}

/** Scope key used to persist user-edited component templates in project.customTypstTemplates. */
export function componentScopeKey(node: ProjectNode): string {
  return `component-${node.id}`
}

/** Default Typst code for components. */
export function defaultComponentTypstSource(): string {
  return defaultComponentTemplate
}

/**
 * Older saved component templates forced every child item onto a fresh page.
 * Remove only that exact legacy break, preserving every other user edit and
 * any page breaks the estimator deliberately added elsewhere.
 */
export function migrateComponentItemFlow(source: string): string {
  return source.replace(
    /(#for\s+item\s+in\s+EE\.items\s*\[\s*)#pagebreak\(\)\s*/m,
    '#pagebreak()\n$1'
  )
}

/**
 * Gathers all child items for a component or subcomponent.
 * If `node` is a component, gathers its direct items and any items in its subcomponents.
 */
export function collectComponentItems(node: ProjectNode): ProjectNode[] {
  const items: ProjectNode[] = []
  for (const child of node.children) {
    if (child.kind === 'item') {
      items.push(child)
    } else if (child.kind === 'subcomponent') {
      for (const subChild of child.children) {
        if (subChild.kind === 'item') {
          items.push(subChild)
        }
      }
    }
  }
  return items
}

/**
 * Returns all direct items that belong directly to this section (for the primary abstract).
 */
export function directComponentItems(node: ProjectNode): ProjectNode[] {
  return node.children.filter((child) => child.kind === 'item')
}

/**
 * Collects all virtual shadow files (drawings, charts, embedded images)
 * across all child items of this component.
 */
export function componentShadowFiles(
  project: EestimateProject,
  node: ProjectNode
): Record<string, string> {
  const shadowFiles: Record<string, string> = {}
  const freshNode = project?.root ? findNode(project.root, node.id) ?? node : node
  const allItems = collectComponentItems(freshNode)

  for (const item of allItems) {
    const effectiveRange = item.print?.range ?? usedCellRange(item.spreadsheet, item.finalCell)
    const itemFiles = itemSheetShadowFiles(item, effectiveRange, { scopePrefix: true })
    for (const [path, data] of Object.entries(itemFiles)) {
      if (data && typeof data === 'string' && data.trim()) {
        shadowFiles[path] = data
      }
    }
  }

  return shadowFiles
}

/**
 * Builds the complete JSON runtime data passed to `sys.inputs["ee-data"]`
 * when compiling the Component Report.
 */
export function buildComponentRenderData(
  project: EestimateProject,
  node: ProjectNode,
  recipes: Record<string, RateAnalysisRecipe> = {},
  rateOf: (item: ProjectNode) => number | undefined = () => undefined,
  options?: { itemScope?: 'all' | 'direct' }
): ComponentRenderData {
  const freshNode = project?.root ? findNode(project.root, node.id) ?? node : node
  const isSub = freshNode.kind === 'subcomponent'
  const directItems = directComponentItems(freshNode)
  const subcomponents = isSub ? [] : freshNode.children.filter((c) => c.kind === 'subcomponent')
  const total = componentItemsTotal(project, freshNode, rateOf, true)
  const availableShadowFiles = componentShadowFiles(project, freshNode)
  const itemScope = options?.itemScope ?? 'all'

  // 1. Build Abstract Rows for Direct Items
  const abstractRows: ComponentAbstractRowData[] = directItems.map((item, index) => {
    const final = getItemFinal(project, item, rateOf(item), true)
    const rawQty = final.qty
    const rawRate = final.rate
    const rawAmount = final.amount

    return {
      sl: String(index + 1),
      code: item.itemCode ?? '',
      heading: nodeDisplayName(item),
      description: item.itemDescription || '',
      qty: rawQty != null ? qtyFmt.format(rawQty) : '—',
      rawQty,
      unit: item.unit ?? final.unit ?? '',
      rate: rawRate != null ? money.format(rawRate) : '—',
      rawRate,
      amount: rawAmount != null ? money.format(rawAmount) : '—',
      rawAmount
    }
  })

  // 2. Build Abstract Rows for Sub-components (if main component)
  subcomponents.forEach((subcomponent, index) => {
    const subTotal = componentItemsTotal(project, subcomponent, rateOf, true)
    abstractRows.push({
      sl: `S${index + 1}`,
      code: subcomponent.itemCode ?? '',
      heading: subcomponent.name,
      description: 'Sub-component · separate General Abstract follows',
      qty: '1',
      rawQty: 1,
      unit: 'LS',
      rate: money.format(subTotal),
      rawRate: subTotal,
      amount: money.format(subTotal),
      rawAmount: subTotal
    })
  })

  // 3. Child Items Data & Gallery Aggregation
  const allGallery: ItemMediaItem[] = []
  const allImages: ItemMediaItem[] = []
  const childItems = itemScope === 'direct' ? directItems : collectComponentItems(freshNode)
  const items: ComponentChildItemData[] = childItems.map((item) => {
    const isDoc = item.itemEditorType === 'document'
    const settings = resolveNodeSettings(project.root, item.id)
    const printConfig = item.print ?? {}

    let univerData: unknown = undefined
    let docData: unknown = undefined
    let rawImages: unknown[] = []

    if (isDoc) {
      docData = item.documentData
        ? parseDocumentToTypstData(item.documentData, item.documentPrintArea, item.documentFinal)
        : undefined
      const extracted = extractDocumentMedia(item)
      rawImages = extracted.images
      if (Array.isArray(extracted.gallery)) allGallery.push(...extracted.gallery)
      if (Array.isArray(extracted.images)) allImages.push(...extracted.images)
    } else {
      univerData = createUniverWorkbookData(item)
      const range = item.print?.range ?? usedCellRange(item.spreadsheet, item.finalCell)
      const extracted = extractItemMedia(item, range, { scopePrefix: true })
      rawImages = extracted.images
      if (Array.isArray(extracted.gallery)) allGallery.push(...extracted.gallery)
      if (Array.isArray(extracted.images)) allImages.push(...extracted.images)
    }

    // Defensive guarantee: Only images whose path is confirmed present in shadowFiles
    // are passed to Typst's #image() call. This guarantees Typst will never throw
    // "file not found" even if an item has an orphaned or missing image resource.
    const verifiedImages = rawImages.filter((img) => {
      const p = (img as { path?: string })?.path
      return typeof p === 'string' && p.length > 0 && Boolean(availableShadowFiles[p])
    })

    return {
      id: item.id,
      code: item.itemCode ?? '',
      name: nodeDisplayName(item),
      unit: item.unit ?? '',
      description: item.itemDescription || '',
      descriptionRuns: resolveItemDescriptionRuns(project, item),
      editorType: isDoc ? 'document' : 'spreadsheet',
      templateGenerated: Boolean(item.templateGenerated),
      univer: univerData,
      document: docData,
      printConfig: {
        pageSize: (printConfig.pageSize ?? settings.pageSize ?? 'A4').toLowerCase(),
        orientation: (printConfig.orientation ?? settings.orientation ?? 'portrait').toLowerCase(),
        margins: printConfig.margins ?? settings.margins ?? { top: 20, right: 15, bottom: 20, left: 25 },
        range: printConfig.range
          ? {
              startRow: Number(printConfig.range.startRow) || 0,
              startColumn: Number(printConfig.range.startColumn) || 0,
              endRow: Number(printConfig.range.endRow) || 0,
              endColumn: Number(printConfig.range.endColumn) || 0
            }
          : null,
        repeatHeaderRows: Number(printConfig.repeatHeaderRows) || 0,
        showGridlines: printConfig.showGridlines ?? true
      },
      images: verifiedImages
    }
  })

  // 4. Signatures
  const signatureSettings = resolveSignatureFooter(project, freshNode.id)
  const signatureRows = signatureSettings.enabled
    ? printableSignatureRows(signatureSettings)
    : []

  return {
    project: project.meta.name,
    component: {
      id: freshNode.id,
      name: freshNode.name,
      code: freshNode.itemCode ?? '',
      isSubcomponent: isSub,
      totalCost: total,
      totalFormatted: money.format(total)
    },
    abstract: abstractRows,
    items,
    signature: signatureRows,
    gallery: allGallery,
    images: allImages
  }
}

/**
 * Typst prelude injected at compile time before the user template.
 * Includes:
 * - Signature block helpers
 * - Rich formatting runs (#render-runs, #render-description)
 * - Univer Spreadsheet renderer (#render-univer-sheet)
 * - Univer Document renderer (#render-univer-doc)
 * - Component Abstract & Item helpers (#render-component-abstract, #render-component-item)
 */
export function componentCompilePrelude(): string {
  return `${EE_ITEM_TABLE_PRELUDE}

${univerComponentPrelude}
`
}

/**
 * Resolves document settings for a component, checking:
 * 1. Saved Typst template block (`// E-Estimate document settings: begin ... end`)
 * 2. Node settings
 * 3. Project defaults
 */
export function resolveComponentDocumentSettings(
  project: EestimateProject,
  node: ProjectNode
): DocumentSettings {
  const savedSource = project.printStudioDocuments?.[componentScopeKey(node)]
  if (savedSource) {
    const parsed = parseDocumentSettingsFromTypst(savedSource)
    if (parsed) return parsed
  }

  // Project print settings are the baseline; node-tree overrides sit on top.
  const projectSettings = resolveProjectDocumentSettings(project.projectPrintSettings)
  const overrides = resolveNodeSettingsOverrides(project.root, node.id)
  return normalizeDocumentSettings(
    {
      pageSize: overrides.pageSize ?? projectSettings.pageSize,
      orientation: overrides.orientation ?? projectSettings.orientation,
      margins: overrides.margins ?? projectSettings.margins,
      fontFamily: projectSettings.fontFamily,
      fontSizePt: projectSettings.fontSizePt * (overrides.reportFontPercent ?? 100) / 100
    },
    projectSettings
  )
}

export interface ComponentPrintPart {
  scopeKey: string
  label: string
  defaultTypstSource: string
  savedTypstSource?: string
  source: string
  compileInputs: Record<string, string>
  shadowFiles: Record<string, string>
  compilePrelude: string
  runtimeData: ComponentRenderData
  projectDocumentSettings: DocumentSettings
  savedDocumentSettings: DocumentSettings | null
}

const EXTERNAL_ITEMS_LOOP = `

#for item in EE.items [
  #if not item.at("templateGenerated", default: false) [
    #render-component-item(item)
    #v(12pt)
  ]
]
`

/**
 * Template layouts own their generated measurement items, but an estimator may
 * add normal item sheets at any time after that layout was saved. Keep those
 * external sheets dynamic instead of requiring the saved Typst source to be
 * reset whenever a child is added.
 */
export function ensureTemplateExternalItems(
  source: string,
  renderData: ComponentRenderData
): string {
  const hasExternal = renderData.items.some((item) => !item.templateGenerated)
  const alreadyPrintsItems =
    /#for\s+(?:\([^)]*\)|[A-Za-z_][\w-]*)\s+in\s+EE\.items\b/.test(source) &&
    /#render-component-item\s*\(/.test(source)
  if (!hasExternal || alreadyPrintsItems) return source

  const signatureMarker = '// Section 3: Signatures'
  const signatureIndex = source.indexOf(signatureMarker)
  return signatureIndex >= 0
    ? `${source.slice(0, signatureIndex).trimEnd()}${EXTERNAL_ITEMS_LOOP}\n${source.slice(signatureIndex)}`
    : `${source.trimEnd()}${EXTERNAL_ITEMS_LOOP}`
}

/**
 * The exact Typst payload Component Print Studio compiles: saved source if the
 * estimator edited it, otherwise the default component (or bund/guide-wall) layout.
 */
export function resolveComponentPrintPart(
  project: EestimateProject,
  node: ProjectNode,
  recipes: Record<string, RateAnalysisRecipe> = {},
  rateOf: (item: ProjectNode) => number | undefined = () => undefined,
  options?: { itemScope?: 'all' | 'direct' }
): ComponentPrintPart {
  const scopeKey = componentScopeKey(node)
  const storedTypstSource = project.printStudioDocuments?.[scopeKey]
  const savedTypstSource = storedTypstSource
  const isBund = node.templateId === 'bund' && Boolean(node.bund)
  const isGuideWall = node.templateId === 'guide-wall' && Boolean(node.guideWall)
  const renderData = buildComponentRenderData(project, node, recipes, rateOf, options)

  let defaultTypst = defaultComponentTypstSource()
  let compileInputs = { 'ee-data': JSON.stringify(renderData) }
  let prelude = componentCompilePrelude()
  if (isBund) {
    defaultTypst = injectBundLayout(defaultComponentTypstSource(), { ...project, printStudioDocuments: undefined }, node, renderData)
    compileInputs = { ...compileInputs, ...bundCompileInputs(project, node) }
    prelude = `${prelude}\n${bundVariablesPrelude()}`
  } else if (isGuideWall) {
    defaultTypst = injectGuideWallLayout(defaultComponentTypstSource(), { ...project, printStudioDocuments: undefined }, node, renderData)
    compileInputs = { ...compileInputs, ...guideWallCompileInputs(project, node, recipes) }
    prelude = `${prelude}\n${guideWallVariablesPrelude()}`
  }

  const projectDocumentSettings = resolveComponentDocumentSettings(project, node)
  const savedDocumentSettings = savedTypstSource
    ? parseDocumentSettingsFromTypst(savedTypstSource)
    : null
  let source = savedTypstSource
    ?? applyDocumentSettingsToTypst(defaultTypst, projectDocumentSettings)
  if ((isBund || isGuideWall) && savedTypstSource) {
    source = ensureTemplateExternalItems(source, renderData)
  }

  return {
    scopeKey,
    label: node.name,
    defaultTypstSource: defaultTypst,
    savedTypstSource,
    source,
    compileInputs,
    shadowFiles: componentShadowFiles(project, node),
    compilePrelude: prelude,
    runtimeData: renderData,
    projectDocumentSettings,
    savedDocumentSettings
  }
}
